#!/bin/bash
#PBS -l nodes=8,cput=01:10:00,walltime=01:10:00 
#node1+node2+node3+node4+node5
# execute with "qsub mosaic.pbs"

cd $PBS_O_WORKDIR
export MPIEXEC_TIMEOUT=300

mpiexec -np 16 -machinefile $PBS_NODEFILE -timestamp-output python main.py NScrapers 1 NPlacers 14 per_page 500 iters 10 MaxTilesVert 32 fidelity 5 &> log
#mpiexec -np 5 -machinefile $PBS_NODEFILE -timestamp-output python main.py NScrapers 1 NPlacers 3 per_page 10 iters 2 MaxTilesVert 16 fidelity 1 &> log
