#!/bin/bash
#PBS -l nodes=3,cput=00:10:00,walltime=00:10:00 
#node1+node2+node3+node4+node5
# execute with "qsub mosaic.pbs"

cd $PBS_O_WORKDIR
export MPIEXEC_TIMEOUT=300

#mpiexec -np 3 -machinefile $PBS_NODEFILE python main.py NScrapers 1 NPlacers 1 per_page 10 pages 1 MaxTilesVert 6 &> log
mpiexec -np 3 -machinefile $PBS_NODEFILE -timestamp-output python main.py NScrapers 1 NPlacers 1 per_page 100 pages 1 MaxTilesVert 64 &> log
